MyProjectShopApp.UI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyProjectShopApp.Business.Abstract;
using MyProjectShopApp.UI.Models;

namespace MyProjectShopApp.UI.Controllers
{
    public class ShopController : Controller
    {

        private IProductService _productService;

        public ShopController(IProductService productService)
        {
            _productService = productService;
        }

       

        public IActionResult List(string category,int page=1)
        {
            const int pageSize = 3;

            return View(new ProductListModel() {
                
                pages = new Pages()
                {
                    TotalItems=_productService.getbycategory(category),
                    WhoPage=page,
                    ItemPage=pageSize,
                    ActiveCategory=category
                    


                },
                
                Products=_productService.GetByCategory(category,page, pageSize) });
        }

        public IActionResult Details(int? id)
        {

            if (id==null)
            {
                return NotFound();
            }

            var product = _productService.GetProductDetails((int)id);

            ProductDetailsModel model = new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList()


            };


            return View(model);
        }
    }
}

MyProjectShopApp.UI/ViewComponent/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyProjectShopApp.Business.Abstract;
using MyProjectShopApp.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyProjectShopApp.UI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {

        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            
            
            return View(new CategoryListViewModel() {
                
                
                Categories=_categoryService.GetAll(),
                SelectedCategory=RouteData.Values["category"]?.ToString()
            
            
            });
        }
    }
}

MyProjectShopApp.UI/Views/Shop/Details.cshtml
@model MyProjectShopApp.UI.Models.ProductDetailsModel
@{
    ViewData["Title"] = "Details";
}


    <div class="row">

      


        <div class="col-md-4">

            <img src="~/IMG/@Model.Product.ImgURL"  class="w-100"/>

        </div>

        <div class="col-md-8">

            <h1 class="mb-3">@Model.Product.ProductName</h1>

            @foreach (var item in Model.Categories)
            {
                <a href="#" class="btn btn-link p-0 mb-3">@item.CategoryName</a>
            }

            <div class="mb-3">
                <h4 class="text-primary">@Model.Product.Price</h4>
            </div>
            <form asp-action="AddToCard" asp-controller="Card" method="post">

                <input type="hidden" name="ProductID" value="@Model.Product.ID" />

                <div class="input-group">

                    <input type="number" name="Quantity" value="1" min="1" step="1" class="form-control" style="width:100px" />

                    <div class="input-group-append">

                        <button type="submit" class="btn btn-success  btn-sm float-right"><i class="fas fa-credit-card pl-2"></i>Add To Card</button>

                    </div>

                </div>
            

            </form>



        </div>

    </div>

<div class="row">

    <div class="col-md-12">
        <p class="p-3">

            @Model.Product.ProductDescription

        </p>


    </div>


</div>

MyProjectShopApp.UI/Views/Shop/List.cshtml
@model MyProjectShopApp.UI.Models.ProductListModel
@{
    ViewData["Title"] = "List";
}



    <div class="row">

        <div class="col-md-3">

            @await Component.InvokeAsync("CategoryList")

        </div>




        <div class="col-md-9">


            <div class="row">

                @foreach (var item in Model.Products)
                {
                    <partial name="_ProductList" for="@item" />
                }

            </div>

            <div pages="@Model.pages"></div>


        </div>



    </div>